version: 1

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: url-shortener-build
          ContainerPort: 8080

Hooks:
  - BeforeInstall: []
  - AfterInstall: []
  - AfterAllowTestTraffic: []
  - BeforeAllowTraffic: []
  - AfterAllowTraffic: []