name: Trigger CodePipeline
on:
  push:
    path:
      - 'app/**'
permissions:
  id-token: write


jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2

    steps:
      - name: checkout code
        uses: actions/checkout@v3

        # --AWS OIDC loginnn
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN1 }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Trigger CodePipeLine
        run: |
          aws codepipeline start-pipeline-execution \
            --name url-shortener-pipeline